### ISSUE TITLE
Missing module and then a problem...

### ISSUE THREAD

**Issue by DarrenPIngram** [ben-hampson/1Password-Deduplicator#3]
When installing your application on MacOS/Python 3.12 it seems that the module tldextract was either not included in the installation, not called or something else. It didn't give any errors in any case until I manually installed it with pip after getting a runtime error.

```
python -m 1password_deduplicator -d                                     
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/di/Applications/1Password-Deduplicator/1password_deduplicator.py", line 2, in <module>
    import tldextract
ModuleNotFoundError: No module named 'tldextract'

```
After that I ran it, then enabled the desktop app integration and authorised it [1Password8, latest version] and get the following error.

```
python -m 1password_deduplicator -d
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/di/Applications/1Password-Deduplicator/1password_deduplicator.py", line 188, in <module>
    run(items)
  File "/Users/di/Applications/1Password-Deduplicator/1password_deduplicator.py", line 125, in run
    if domains(new_item) != domains(existing_item) and password(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/di/Applications/1Password-Deduplicator/1password_deduplicator.py", line 31, in domains
    s.add(".".join(p for p in d if p))
                  ^^^^^^^^^^^^^^^^^^^
TypeError: 'ExtractResult' object is not iterable
```
At that point I'm a little stumped!

**Comment by ben-hampson** [comment]
For the first error, did you run
`pip install -r requirements.txt`
before running 
`python -m 1password_deduplicator -d`?

`requirements.txt` contains `tldextract==3.4.0` so it should have installed it.

For the second error, I'll have to look into that. I see `tldextract` is now up to version 5.1.2 so perhaps try
```
pip uninstall tldextract
pip install tldextract==3.4.0
```
